### ISSUE TITLE
Improvements on last commit

### ISSUE THREAD

**Issue by stephdotnet** [purplena/php-practitioner#10]
- Make a pull request for this issues
- Fix the comments i made on your last commit : https://github.com/purplena/php-practitioner/commit/da6b7fd45512e41daba5434e11f0bc058150fd6d
- Fin a way to properly display the weather on tomorrow noon forecast
- Change your forecast api key and put it in your .env (+ update .env.example)

**Comment by purplena** [comment]
Closed with commit [bd6b424](https://github.com/purplena/php-practitioner/commit/bd6b424ea2a74900ff93795584caa2ff0948d135)
